### PR TITLE
Fix for SSR

### PR DESCRIPTION
**Pull request by homerjam**
I had to make these changes to use with Nuxt

### CODE REVIEW

**Comment by elpete** [comment]
If you don't want to use `mounted`, you can stick with `created` and use Nuxt's `no-ssr` component.

The `HTMLElement` reference still needs to be changed to support Nuxt, even with the `no-ssr` component.

**Comment by tkjaergaard** [comment]
Let's try to figure this one out so that the package can support SSR and NUXT.

I'll give it a go updating the tests and source based on this PR 👍

**Comment by Atinux** [comment]
Any updates on this 😄 ?

**Comment by wouterkroes** [comment]
What exactly is the status of this PR?

@tkjaergaard @homerjam I have created a different version to support SSR. I have kept the `created` functionality in place but added a defensive check for `HTMLElement`. Is this an acceptable solution => https://github.com/heavyy/vue-intersect/pull/9
* If this is a acceptable solution I will (try to) fix the tests


* @elpete I tried the [no-ssr](https://github.com/egoist/vue-no-ssr) component but I still get a `HTMLElement is not defined` SSR error :(

**Comment by homerjam** [comment]
Thanks @wouterkroes. Personally I think it makes more sense to use `mounted` as it will keep things simpler.

I've ended up with my own component borrowing from this one - homerjam/vuxtras

**Comment by tkjaergaard** [comment]
Closed by #13

**Pull request closed without merging**
